### ISSUE TITLE
minimum alignment score options ignored

### ISSUE THREAD

**Issue by good-ligations** [hanyue36/nanoplexer#10]
It seems that the "-s" option for the alignment score is unused or I may be entering it incorrectly. I have tried multiple rounds with varying "s" scores above the default of "22", and the alignment score values are not changed in the log or in the amount of demultiplexed samples. 

Command:
$ ./nanoplexer/nanoplexer -b ./barcodes.fa -d sample.txt -s 40 -p ./output -l log ../FAO23974_pass_ced4ad01_125.fastq

stdout:
2022-02-07 13:57:02 Minimal alignment score is 22
2022-02-07 13:57:04 Finished demultiplexing sequence data.

$ head log:
0f900e08-52dd-4cb7-a5df-4ec45b9464ef	REVERSE10	+	42	H_REV	+	42
1e1e0c4c-21cf-41d6-af1c-d63bd591d8ea	REVERSE01	+	33	A_REV	+	29
19be82b8-1094-4b90-8cf5-1db5d045f484	REVERSE02	+	42	E_REV	+	42
c8a67fd7-29d2-4374-b4ab-3243d4647ffe	REVERSE03	+	31	A_REV	+	42
4de7e4c5-e8e2-4ee0-8a0c-708ad3a7a31b	REVERSE01	+	42	F_REV	+	42
069fd321-f80c-4cb1-91c1-1e7196597bcf	H	+	42	REVERSE08_REV	+	32
e6df5bca-c01f-402f-9f6c-f3837786a1b0	E	+	42	REVERSE03_REV	+	34
aa3a79b1-1691-4350-bc51-362188635966	REVERSE02	+	32	E_REV	+	42
20161ea4-e32a-4da1-bafa-63e4602202fe	REVERSE01	+	28	D_REV	+	38
c461726f-5090-4c11-94f8-3ce608865f4d	REVERSE01	+	42	F_REV	+	42

**Comment by hanyue36** [comment]
If you want to specify minimal alignment score, use -i and -s simultaneously.

**Comment by good-ligations** [comment]
Thank you that worked perfectly! This program works very well for Nanopore datasets!

Are there any options to trim all bases upstream of the forward barcode and downstream of the reverse?

Thank you!

**Comment by hanyue36** [comment]
I didn't design the trim option and the barcode sequences should be shown as soft clipping in cigar flag after alignment. I think it doesn't affect downstream analysis. I'll consider to add the option in further version.
