### ISSUE TITLE
The format of barcode.fa

### ISSUE THREAD

**Issue by wuhao08** [hanyue36/nanoplexer#9]
i am a new in nanopore data analysis, i am wondering the format of barcode.fa. Could u please show me a sample of barcode.fa？ or would it works if i just prepare the barcode.fa as the FASTA format, like that?
![1631624064(1)](https://user-images.githubusercontent.com/53133331/133261259-803d8023-c774-441b-98ab-b3fce84a9620.png)

**Comment by hanyue36** [comment]
Standard fasta format should be ok.

**Comment by wuhao08** [comment]
> Standard fasta format should be ok.

Thanks for your reply!
